version: '3'

services:
  app-web: # 服务名称
    image: nginx:latest # nginx镜像名称
    volumes:
      - ./dist:/usr/share/nginx/html # 挂载dist目录到nginx的html目录
      - ./nginx.conf:/etc/nginx/nginx.conf # 挂载nginx配置文件
      - ./logs:/var/log/nginx # 挂载日志目录
    ports:
      - "3005:80" # 端口映射
